artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source: https://github.com/Ankitzanzmera/data_repository/raw/main/hate_speech_data.zip
  local_data_filepath: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/hate_speech_data/

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/hate_speech_data/2020-12-31-DynamicallyGeneratedHateDataset-entries-v0.1.csv
  transformed_data_path: artifacts/data_transformation/final.csv